"""Live e2e ground-truth tests (diag-gated).

Issue #91: the original e2e tests required an operator-private
ground-truth CSV at C:/tmp/ground_truth.csv. The new approach
(commit TBD) bundles a public ground-truth fixture at
tests/fixtures/ground_truth.csv built from dixiedata.db +
ok_pensioners.json. The fixture is regenerated by
scripts/audit/build_ground_truth_fixture.py.

These four tests run the actual FaG searcher against the
bundled fixture (Playwright + stealth + throttle 2.5s) and
evaluate precision/recall/F1. They take 2-3 min per 50
records and depend on a real browser session, so they are
gated by @pytest.mark.diag. They are NOT in the default
suite; run intentionally with:

    pytest -m diag tests/test_e2e_ground_truth_diag.py

The default suite has fast ground-truth fixture validation
tests in tests/test_e2e_ground_truth.py.
"""
import csv
import json
import sys
import time
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from scripts.matching.evaluation import (  
    compute_confusion_matrix,
    best_threshold,
)


pytestmark = pytest.mark.diag


GT_CSV = Path(__file__).parent / "fixtures" / "ground_truth.csv"
GT_OUT_DIR = Path(__file__).parent / "fixtures" / "_e2e_output"
GT_STATE = GT_OUT_DIR / "results.jsonl"

REQUIRES_BUNDLED_GT = pytest.mark.skipif(
    not GT_CSV.exists(),
    reason=(
        f"{GT_CSV} not present. Regenerate via "
        f"python scripts/audit/build_ground_truth_fixture.py."
    ),
)


def _load_gt_index() -> dict[int, dict]:
    """Build pensioner_id -> GT row index. The test joins state
    records to this index externally (the searcher does not
    embed GT in the state.jsonl)."""
    rows = list(csv.DictReader(open(GT_CSV, encoding="utf-8")))
    return {int(r["id"]): r for r in rows}


def _load_state() -> list[dict]:
    """Load the searcher's results.jsonl. The state has its own
    pensioner_id field; we join to GT externally."""
    return [json.loads(line) for line in open(GT_STATE, encoding="utf-8")]


def _ensure_searcher_run():
    """Run the searcher ONCE per session. Subsequent calls are no-ops.

    The searcher takes 2-3 min per run; this fixture is module-scoped
    so all 4 assertions share one run. A sentinel file tracks
    whether the run is fresh.
    """
    import subprocess
    import shutil
    sentinel = GT_STATE.with_suffix(".e2e_sentinel")
    if sentinel.exists():
        return
    if GT_STATE.exists():
        GT_STATE.unlink()
    if GT_OUT_DIR.exists():
        shutil.rmtree(GT_OUT_DIR, ignore_errors=True)
    result = subprocess.run(
        [
            "python", "scripts/run_unified.py",
            "--input-csv", str(GT_CSV),
            "--cgr", str(ROOT / "docs" / "research" / "cgr" / "ok_vets_enriched.jsonl"),
            "--out", str(GT_OUT_DIR),
            "--limit", "10",
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        timeout=1800,  
    )
    if result.returncode != 0:
        pytest.fail(
            f"Searcher failed (rc={result.returncode}): "
            f"{result.stderr[-500:]}"
        )
    sentinel.touch()


@pytest.fixture(scope="module")
def state_records():
    """Module-scoped fixture: run the searcher once, share results."""
    _ensure_searcher_run()
    return _load_state()


def _build_pairs(state, gt_index):
    """For each state record, join to GT and produce (actual, score)
    pairs. `actual` is True iff the searcher's top-ranked candidate
    matches the GT memorial.

    The state record's `common.candidates` (or `ranked_candidates`
    for legacy format) carries the candidates; we extract the
    memorial_id from the top one.
    """
    pairs = []
    for r in state:
        pid = r.get("pensioner_id")
        if pid is None or pid == 0:
            
            
            
            legacy_id = r.get("common", {}).get("id")
            if legacy_id and legacy_id != 0:
                pid = legacy_id
        if pid is None or pid == 0:
            continue
        gt = gt_index.get(pid)
        if gt is None:
            
            continue
        gt_memorial_id = gt.get("_gt_memorial_id")
        actual = False
        
        cands = (
            r.get("ranked_candidates")
            or r.get("common", {}).get("candidates", [])
        )
        if cands:
            top = cands[0]
            top_memorial = (
                top.get("memorial_id")
                or top.get("id")
                or str(top.get("common", {}).get("id", ""))
            )
            actual = str(gt_memorial_id) == str(top_memorial)
        score = r.get("best_score", 0.0)
        pairs.append((actual, score))
    return pairs


@REQUIRES_BUNDLED_GT
def test_e2e_searcher_evaluates_with_confusion_matrix(state_records):
    """End-to-end: searcher's precision/recall/F1 against the
    bundled ground truth. Joins state.jsonl (searcher output)
    to ground_truth.csv externally — the searcher doesn't
    embed GT in its state.

    NOTE: this test runs the full live searcher with Playwright
    + stealth + throttle 2.5s. At --limit 10, expect ~8 min
    per run. At --limit 50, expect ~38 min. The test is
    @pytest.mark.diag gated; not in the default suite.
    """
    gt_index = _load_gt_index()
    pairs = _build_pairs(state_records, gt_index)
    assert len(pairs) > 0, (
        "no state records joined to GT; check the searcher's "
        "pensioner_id emission (the searcher should emit the "
        "ok_pensioners.json id, not 0)"
    )

    result = best_threshold(pairs, metric="f1")
    print(f"\nBest threshold: {result.threshold:.3f}")
    print(f"Precision: {result.precision:.3f}")
    print(f"Recall: {result.recall:.3f}")
    print(f"F1: {result.f1:.3f}")
    print(f"Confusion matrix: {result.confusion_matrix}")

    assert result.f1 > 0.5, (
        f"F1 {result.f1:.3f} below 0.5; searcher may be regressed. "
        f"Run `pytest -m diag tests/test_e2e_ground_truth_diag.py "
        f"-v` for full output."
    )


@REQUIRES_BUNDLED_GT
def test_e2e_rank1_hit_rate(state_records):
    """Of the joined GT records, how many have the right
    answer at rank 1?"""
    gt_index = _load_gt_index()
    pairs = _build_pairs(state_records, gt_index)
    hit1 = sum(1 for actual, _ in pairs if actual)
    pct = hit1 / max(len(pairs), 1) * 100
    print(f"\nRank-1 hits: {hit1}/{len(pairs)} = {pct:.1f}%")
    assert hit1 >= int(0.5 * len(pairs)), (
        f"rank-1 hit rate {pct:.1f}% below 50% (lax threshold "
        f"because the GT comes from the operator's hand-"
        f"curation via dixiedata.db and may include borderline "
        f"matches)"
    )


@REQUIRES_BUNDLED_GT
def test_e2e_auto_accept_precision(state_records):
    """Of the auto-accepts, how many are correct?"""
    gt_index = _load_gt_index()
    auto = [r for r in state_records if r.get("status") == "auto_accept"]
    if not auto:
        pytest.skip("No auto-accepts in this run")
    correct = 0
    for r in auto:
        pid = r.get("pensioner_id")
        gt = gt_index.get(pid, {})
        gt_mid = str(gt.get("_gt_memorial_id", ""))
        cands = r.get("ranked_candidates") or []
        if cands and str(cands[0].get("memorial_id") or
                         cands[0].get("id") or "") == gt_mid:
            correct += 1
    precision = correct / len(auto)
    print(f"\nAuto-accept precision: {correct}/{len(auto)} = "
          f"{precision*100:.1f}%")
    assert precision >= 0.6, (
        f"auto-accept precision {precision*100:.1f}% below 60%"
    )


@REQUIRES_BUNDLED_GT
def test_e2e_in_top_5(state_records):
    """Of the joined GT records, how many are in the top 5?"""
    gt_index = _load_gt_index()
    pairs = _build_pairs(state_records, gt_index)
    top5 = 0
    for r in state_records:
        pid = r.get("pensioner_id")
        gt = gt_index.get(pid, {})
        gt_mid = str(gt.get("_gt_memorial_id", ""))
        cands = r.get("ranked_candidates") or []
        for cand in cands[:5]:
            if str(cand.get("memorial_id") or cand.get("id") or "") == gt_mid:
                top5 += 1
                break
    pct = top5 / max(len(pairs), 1) * 100
    print(f"\nTop-5 hits: {top5}/{len(pairs)} = {pct:.1f}%")
    assert top5 >= int(0.5 * len(pairs)), (
        f"top-5 hit rate {pct:.1f}% below 50%"
    )
