"""EasyOCR run checkpoint watcher.

Fires a git commit + CHANGELOG bullet at 25% / 50% / 75% of the
configured record target so the run's progress is visible in the
git history without committing per-heartbeat (which would spam
~180 commits over 15h).

The watcher:
1. Polls `red_ocr_results.json` every 60s for the easy_text count.
2. On first crossing of a threshold (1343 / 2685 / 4027 by default),
   writes a progress artifact at
   `data/easyocr_runs/checkpoint_<NN>.json` (counts, last heartbeat,
   elapsed wall time) and commits it with a Conventional-Commits
   subject: `chore(ocr): L3 checkpoint at N% (X/Y records)`.
3. Idempotent: re-running the watcher after a threshold has been
   fired is a no-op (a `.fired` marker file in `data/easyocr_runs/`
   tracks which thresholds have landed).

The watcher exits with code 0 when all thresholds are fired
(or 1 on the first unhandled error). The long OCR run is
unaffected — this script only reads the JSON.

Usage::

    python scripts/ingest/easyocr_checkpoint.py
    python scripts/ingest/easyocr_checkpoint.py --target 5369
    python scripts/ingest/easyocr_checkpoint.py --poll 30
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

_SCRIPTS_DIR = Path(__file__).parent
_ROOT = _SCRIPTS_DIR.parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

DEFAULT_JSON = Path("data/cards/red_ocr_results.json")
DEFAULT_LOG = Path("data/easyocr_full_run.log")
DEFAULT_ARTIFACT_DIR = Path("data/easyocr_runs")
DEFAULT_FIRED = DEFAULT_ARTIFACT_DIR / "checkpoints.fired.json"

# Default thresholds. The resumed run has 5369 targets
# (9436 records - 836 already done - 3410 already-dated -
# some missing images = 5369). 25/50/75 land at 1343/2685/4027.
DEFAULT_THRESHOLDS = (25, 50, 75)


def _read_count(path: Path) -> tuple[int, int, int]:
    """Return (records_total, easy_text_count, death_date_count).
    Reads UTF-8 explicitly (cp1252 default on Windows crashes
    on the OCR JSON's 0x9d bytes)."""
    rows = json.loads(path.read_text(encoding="utf-8"))
    return (
        len(rows),
        sum(1 for r in rows if r.get("easy_text")),
        sum(1 for r in rows if r.get("death_date")),
    )


def _read_last_heartbeat(log: Path) -> dict[str, Any]:
    """Pull the last `heartbeat: i=N/M ok=...` line from the run
    log. Returns {} if the log is missing or has no heartbeats yet."""
    if not log.exists():
        return {}
    pat = re.compile(
        r"(?P<ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}),\d+\s+INFO\s+"
        r"heartbeat:\s+(?P<body>.*)"
    )
    last: dict[str, Any] = {}
    with log.open(encoding="utf-8", errors="ignore") as f:
        for line in f:
            m = pat.search(line)
            if m:
                last = {"ts": m["ts"], **dict(
                    kv.split("=", 1) for kv in m["body"].split()
                    if "=" in kv
                )}
    return last


def _load_fired(path: Path) -> list[int]:
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return []


def _save_fired(path: Path, fired: list[int]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".partial")
    tmp.write_text(json.dumps(sorted(fired), indent=2),
                   encoding="utf-8")
    tmp.replace(path)


def _write_changelog_bullet(percent: int, count: int, target: int,
                            heartbeat: dict) -> None:
    """Append a bullet to CHANGELOG.md's [Unreleased] section.
    Uses a one-shot grep + line-splice (the file is too large
    to fully re-parse each checkpoint)."""
    cl = _ROOT / "CHANGELOG.md"
    text = cl.read_text(encoding="utf-8")
    marker = "## [Unreleased]"
    idx = text.find(marker)
    if idx < 0:
        sys.stderr.write("CHANGELOG.md has no [Unreleased] section; "
                         "skipping bullet append\n")
        return
    
    new_heading_pos = text.find("\n## [", idx + 1)
    if new_heading_pos < 0:
        new_heading_pos = len(text)
    rate = heartbeat.get("rate", "?")
    eta = heartbeat.get("eta", "?")
    bullet = (
        f"\n- **EasyOCR L3 checkpoint at {percent}%** "
        f"({count}/{target} records, "
        f"heartbeat rate={rate} eta={eta}s). "
        f"Generated by scripts/ingest/easyocr_checkpoint.py."
    )
    
    if f"EasyOCR L3 checkpoint at {percent}%" in text:
        return
    text = text[:new_heading_pos] + bullet + text[new_heading_pos:]
    cl.write_text(text, encoding="utf-8")


def _git(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args], cwd=str(_ROOT),
        capture_output=True, text=True,
        check=check, encoding="utf-8",
    )


def fire_checkpoint(percent: int, count: int, target: int,
                    heartbeat: dict, artifact_dir: Path) -> str:
    """Write the artifact + CHANGELOG bullet + commit. Returns
    the commit SHA on success, or "" on commit failure."""
    artifact_dir.mkdir(parents=True, exist_ok=True)
    artifact = artifact_dir / f"checkpoint_{percent:02d}.json"
    payload = {
        "percent": percent,
        "count": count,
        "target": target,
        "wall_time_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "last_heartbeat": heartbeat,
    }
    artifact.write_text(json.dumps(payload, indent=2),
                        encoding="utf-8")
    _write_changelog_bullet(percent, count, target, heartbeat)
    _git("add", str(artifact).replace("\\", "/"),
         "CHANGELOG.md",
         str(_ROOT / "data" / "easyocr_runs" / "checkpoints.fired.json"))
    subject = (f"chore(ocr): L3 checkpoint at {percent}% "
               f"({count}/{target} records)")
    proc = _git("commit", "-m", subject, check=False)
    if proc.returncode != 0:
        sys.stderr.write(
            f"git commit failed at {percent}%: {proc.stderr}\n"
        )
        return ""
    sha = _git("rev-parse", "--short", "HEAD",
               check=False).stdout.strip()
    return sha


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--json", type=Path, default=DEFAULT_JSON,
                    help="path to red_ocr_results.json")
    ap.add_argument("--log", type=Path, default=DEFAULT_LOG,
                    help="path to the EasyOCR run log")
    ap.add_argument("--artifact-dir", type=Path,
                    default=DEFAULT_ARTIFACT_DIR,
                    help="where to write the checkpoint JSON")
    ap.add_argument("--fired", type=Path, default=DEFAULT_FIRED,
                    help="path to the fired-thresholds marker file")
    ap.add_argument("--target", type=int, default=0,
                    help="total records expected for this run "
                         "(0 = auto-derive: 9436 - records_with_"
                         "death_date - records_with_easy_text at "
                         "the resumed baseline; not perfectly "
                         "accurate but close)")
    ap.add_argument("--poll", type=int, default=60,
                    help="seconds between polls (default 60)")
    ap.add_argument("--thresholds", type=str, default=",".join(
        str(t) for t in DEFAULT_THRESHOLDS),
                    help="comma-separated percent thresholds "
                         "(default 25,50,75)")
    args = ap.parse_args(argv)

    thresholds = sorted(int(t) for t in args.thresholds.split(","))
    fired = _load_fired(args.fired)
    sys.stderr.write(
        f"[checkpoint] target={args.target} thresholds={thresholds} "
        f"already_fired={fired} poll={args.poll}s\n"
    )

    last_print = 0.0
    while True:
        total, easy_text, _ = _read_count(args.json)
        if args.target <= 0:
            
            target = max(easy_text, 5369)
        else:
            target = args.target

        pct = 100.0 * easy_text / max(target, 1)

        if time.time() - last_print > 300:
            sys.stderr.write(
                f"[checkpoint] easy_text={easy_text}/{target} "
                f"({pct:.1f}%) fired={fired}\n"
            )
            last_print = time.time()

        for t in thresholds:
            if t in fired:
                continue
            if pct >= t:
                heartbeat = _read_last_heartbeat(args.log)
                sha = fire_checkpoint(
                    t, easy_text, target, heartbeat,
                    args.artifact_dir,
                )
                if sha:
                    fired.append(t)
                    _save_fired(args.fired, fired)
                    sys.stderr.write(
                        f"[checkpoint] FIRED {t}% "
                        f"({easy_text}/{target}) -> {sha}\n"
                    )

        if all(t in fired for t in thresholds):
            sys.stderr.write("[checkpoint] all thresholds fired; exiting\n")
            return 0
        time.sleep(args.poll)


if __name__ == "__main__":
    raise SystemExit(main())
